import 'dart:async';
import 'dart:developer' as developer;

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:google_sign_in/google_sign_in.dart';

/// Result of an authentication operation.
enum AuthResult { success, cancelled, error, offline, profileError }

/// A timestamped authentication diagnostic that is also written to Logcat.
class AuthDiagnosticEvent {
  const AuthDiagnosticEvent(this.message, this.timestamp);

  final String message;
  final DateTime timestamp;

  @override
  String toString() => '${timestamp.toIso8601String()}  $message';
}

/// Google Sign-In, Firebase Authentication, and Firestore profile lifecycle.
class AuthService extends ChangeNotifier {
  static const _webClientId =
      '687760012800-njf7ak1fsip6mruit05i7pqb0r9jjdd9.apps.googleusercontent.com';

  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  // Android reads default_web_client_id generated by the Google Services Gradle
  // plugin from google-services.json. Supplying an Android OAuth client here is
  // invalid; an explicit Android serverClientId is therefore intentionally not
  // used. Web still requires its Web OAuth client ID.
  final GoogleSignIn _googleSignIn = GoogleSignIn(
    scopes: const ['email', 'profile'],
    clientId: kIsWeb ? _webClientId : null,
  );

  User? get currentUser => _auth.currentUser;
  String? get uid => currentUser?.uid;
  String? get displayName => currentUser?.displayName;
  String? get photoUrl => currentUser?.photoURL;
  bool get isSignedIn => currentUser != null;
  bool get isAuthenticating => _isAuthenticating;
  bool get profileReady => _profileReady;
  String? get username => _username;
  String? get lastError => _lastError;
  String get diagnosticReport => _diagnostics.join('\n');
  List<AuthDiagnosticEvent> get diagnostics => List.unmodifiable(_diagnostics);

  bool _isAuthenticating = false;
  bool _profileReady = false;
  String? _username;
  String? _lastError;
  final List<AuthDiagnosticEvent> _diagnostics = [];

  StreamSubscription<DocumentSnapshot<Map<String, dynamic>>>? _userDocSub;
  StreamSubscription<User?>? _authStateSub;
  StreamSubscription<User?>? _idTokenSub;
  StreamSubscription<User?>? _userChangesSub;

  AuthService() {
    _log(
        'AUTH INIT ✓ GoogleSignIn configured (platform=${kIsWeb ? 'web' : 'native'})');
    _authStateSub = _auth.authStateChanges().listen(
      (user) {
        _log('AUTH STREAM authStateChanges fired: uid=${user?.uid ?? 'null'}');
        _handleAuthState(user);
      },
      onError: (Object error, StackTrace stack) =>
          _recordStreamError('authStateChanges', error, stack),
    );
    _idTokenSub = _auth.idTokenChanges().listen(
          (user) => _log(
              'AUTH STREAM idTokenChanges fired: uid=${user?.uid ?? 'null'}'),
          onError: (Object error, StackTrace stack) =>
              _recordStreamError('idTokenChanges', error, stack),
        );
    _userChangesSub = _auth.userChanges().listen(
          (user) =>
              _log('AUTH STREAM userChanges fired: uid=${user?.uid ?? 'null'}'),
          onError: (Object error, StackTrace stack) =>
              _recordStreamError('userChanges', error, stack),
        );
  }

  void _log(String message) {
    final event = AuthDiagnosticEvent(message, DateTime.now());
    _diagnostics.add(event);
    if (_diagnostics.length > 100) _diagnostics.removeAt(0);
    developer.log(message, name: 'Yourself.Auth');
    debugPrint('[Yourself.Auth] $message');
  }

  void _recordStreamError(String stream, Object error, StackTrace stack) {
    _log('AUTH STREAM $stream ✗ ${error.runtimeType}: $error\n$stack');
    _lastError = '$stream failed: ${error.runtimeType}: $error\n\n$stack';
    notifyListeners();
  }

  void _handleAuthState(User? user) {
    _userDocSub?.cancel();
    _userDocSub = null;
    _username = null;
    _profileReady = false;
    if (user != null) {
      _userDocSub = _db.collection('users').doc(user.uid).snapshots().listen(
        (doc) {
          final data = doc.data();
          _username = data?['username'] as String?;
          _profileReady = doc.exists;
          _log('FIRESTORE STREAM ✓ users/${user.uid} exists=${doc.exists}');
          notifyListeners();
        },
        onError: (Object error, StackTrace stack) =>
            _recordStreamError('users/${user.uid}', error, stack),
      );
    }
    notifyListeners();
  }

  /// Signs in and does not report success until Firebase Auth and the Firestore
  /// profile are both verified.
  Future<AuthResult> signInWithGoogle() async {
    if (_isAuthenticating) return AuthResult.error;
    _isAuthenticating = true;
    _profileReady = false;
    _lastError = null;
    _diagnostics.clear();
    _log('STEP 0 ✓ Google Sign-In flow started');
    notifyListeners();

    try {
      _log('STEP 1 → Opening Google account picker');
      final googleAccount = await _googleSignIn.signIn();
      if (googleAccount == null) {
        _log(
            'STEP 2 ✗ GoogleSignIn.signIn returned null (cancelled/no account)');
        _lastError =
            'Google did not return an account. The sign-in was cancelled or rejected before tokens were issued.';
        return AuthResult.cancelled;
      }
      _log('STEP 2 ✓ Google account selected: ${googleAccount.email}');

      _log('STEP 3 → Requesting Google authentication tokens');
      final googleAuth = await googleAccount.authentication;
      final hasIdToken = googleAuth.idToken?.isNotEmpty == true;
      final hasAccessToken = googleAuth.accessToken?.isNotEmpty == true;
      _log('STEP 3 ${hasIdToken ? '✓' : '✗'} idToken received=$hasIdToken');
      _log(
          'STEP 4 ${hasAccessToken ? '✓' : '✗'} accessToken received=$hasAccessToken');
      if (!hasIdToken) {
        throw StateError(
          'Google returned no ID token. Android must use the Web OAuth client generated as default_web_client_id from google-services.json.',
        );
      }

      final credential = GoogleAuthProvider.credential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );
      _log('STEP 5 ✓ Firebase Google credential created');

      _log('STEP 6 → Calling FirebaseAuth.signInWithCredential');
      final userCredential = await _auth.signInWithCredential(credential);
      final firebaseUser = userCredential.user;
      if (firebaseUser == null) {
        throw StateError(
            'Firebase returned a null user after signInWithCredential.');
      }
      _log(
          'STEP 6 ✓ FirebaseAuth credential accepted; uid=${firebaseUser.uid}');
      _log('STEP 7 ✓ FirebaseAuth.currentUser uid=${_auth.currentUser?.uid}');

      try {
        await ensureUserProfile(firebaseUser);
      } on FirebaseException catch (error, stack) {
        _recordFailure('STEP 8 FIRESTORE PROFILE FAILED', error, stack);
        return AuthResult.profileError;
      }

      _log('STEP 9 ✓ Authentication and profile verification complete');
      return AuthResult.success;
    } on FirebaseAuthException catch (error, stack) {
      _recordFailure(
        'FIREBASE AUTH FAILED code=${error.code} message=${error.message}',
        error,
        stack,
      );
      return AuthResult.error;
    } on PlatformException catch (error, stack) {
      // Google Play services ApiException values (for example status 10) are
      // delivered to Flutter as PlatformException by google_sign_in_android.
      _recordFailure(
        'PLATFORM/API FAILED code=${error.code} message=${error.message} details=${error.details}',
        error,
        stack,
      );
      return error.code == 'network_error'
          ? AuthResult.offline
          : AuthResult.error;
    } on Exception catch (error, stack) {
      // Native Google ApiException and SocketException are bridged through
      // platform channels on Android. Identify both explicitly without a
      // dart:io import, which would break the web build.
      final kind = error.runtimeType.toString();
      final prefix = kind.contains('SocketException')
          ? 'SOCKET/OFFLINE FAILED'
          : kind.contains('ApiException')
              ? 'GOOGLE API FAILED'
              : 'AUTH EXCEPTION FAILED';
      _recordFailure(prefix, error, stack);
      return kind.contains('SocketException')
          ? AuthResult.offline
          : AuthResult.error;
    } catch (error, stack) {
      _recordFailure('UNKNOWN AUTH FAILURE', error, stack);
      return AuthResult.error;
    } finally {
      _isAuthenticating = false;
      notifyListeners();
    }
  }

  void _recordFailure(String stage, Object error, StackTrace stack) {
    final full =
        '$stage\nType: ${error.runtimeType}\nError: $error\nStack trace:\n$stack';
    _lastError = full;
    _log(full);
  }

  Future<void> ensureUserProfile(User user) async {
    final ref = _db.collection('users').doc(user.uid);
    _log('STEP 8 → Verifying Firestore profile users/${user.uid}');
    final snapshot = await ref.get();
    if (!snapshot.exists) {
      await ref.set({
        'uid': user.uid,
        'displayName': user.displayName ?? '',
        'photoUrl': user.photoURL ?? '',
        'username': null,
        'createdAt': FieldValue.serverTimestamp(),
      });
      _log('STEP 8 ✓ Firestore profile created at users/${user.uid}');
    } else {
      await ref.update({
        'displayName': user.displayName ?? '',
        'photoUrl': user.photoURL ?? '',
      });
      _log('STEP 8 ✓ Existing Firestore profile verified at users/${user.uid}');
    }
    final verification = await ref.get(const GetOptions(source: Source.server));
    if (!verification.exists) {
      throw StateError(
          'Firestore profile write completed but server verification failed.');
    }
    _profileReady = true;
    notifyListeners();
  }

  Future<void> signOut() async {
    _lastError = null;
    try {
      _log('SIGN OUT → Disconnecting Google account');
      await _googleSignIn.disconnect().catchError((Object error) {
        _log('SIGN OUT Google disconnect warning: $error');
        return null;
      });
      await _auth.signOut();
      _log('SIGN OUT ✓ Firebase and Google sessions cleared');
    } catch (error, stack) {
      _recordFailure('SIGN OUT FAILED', error, stack);
      rethrow;
    } finally {
      notifyListeners();
    }
  }

  Future<bool> claimUsername(String desired) async {
    _lastError = null;
    final name = desired.trim().toLowerCase();
    if (!RegExp(r'^[a-z0-9_]{3,20}$').hasMatch(name)) {
      _lastError =
          'Username must be 3-20 chars: lowercase letters, numbers, underscore.';
      return false;
    }
    final currentUid = uid;
    if (currentUid == null) {
      _lastError = 'You must be signed in to claim a username.';
      return false;
    }
    try {
      final userRef = _db.collection('users').doc(currentUid);
      final userSnapshot = await userRef.get();
      final existingUsername = userSnapshot.data()?['username'] as String?;
      if (existingUsername?.isNotEmpty == true) {
        _lastError = 'You already have a username and cannot change it.';
        return false;
      }
      final result = await _db.runTransaction((transaction) async {
        final nameRef = _db.collection('usernames').doc(name);
        final nameSnapshot = await transaction.get(nameRef);
        if (nameSnapshot.exists) {
          return nameSnapshot.data()?['uid'] == currentUid;
        }
        transaction.set(nameRef, {
          'uid': currentUid,
          'claimedAt': FieldValue.serverTimestamp(),
        });
        transaction.update(userRef, {'username': name});
        return true;
      });
      if (!result) _lastError = 'That username is already taken.';
      return result;
    } catch (error, stack) {
      _recordFailure('CLAIM USERNAME FAILED', error, stack);
      return false;
    } finally {
      notifyListeners();
    }
  }

  @override
  void dispose() {
    _userDocSub?.cancel();
    _authStateSub?.cancel();
    _idTokenSub?.cancel();
    _userChangesSub?.cancel();
    super.dispose();
  }
}
