// File generated by hand. Firebase config for project habit-tracker-37dc1.
//
// NOTE: The Web API key / appId below are placeholders. If the real values
// are missing, Firebase.initializeApp() is wrapped in try/catch in main()
// and the app degrades gracefully to offline-only mode.
//
// For Android, configuration is provided by google-services.json (if present
// at android/app/google-services.json). The google-services Gradle plugin is
// applied conditionally in build.gradle.kts.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholder-web-key',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'habit-tracker-37dc1',
    authDomain: 'habit-tracker-37dc1.firebaseapp.com',
    storageBucket: 'habit-tracker-37dc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholder-android-key',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'habit-tracker-37dc1',
    storageBucket: 'habit-tracker-37dc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholder-ios-key',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'habit-tracker-37dc1',
    storageBucket: 'habit-tracker-37dc1.appspot.com',
    iosBundleId: 'com.yourself.habits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholder-macos-key',
    appId: '1:000000000000:macos:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'habit-tracker-37dc1',
    storageBucket: 'habit-tracker-37dc1.appspot.com',
    iosBundleId: 'com.yourself.habits',
  );
}
